spring.datasource.url=jdbc:postgresql://localhost:5432/citas_medicas
spring.datasource.username=citas_user
spring.datasource.password=change_me
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
